### PR TITLE
Enemy behaviour

### PR DESCRIPTION
**Pull request by stathampen**

### CODE REVIEW

**Comment by stathampen** [comment]
DONT MERGE IN JUST YET IM FIXING THINGS

**Comment by stathampen** [comment]
READY TO MERGE

**Comment by JonathanMCarter** [comment]
Pretty much jsut wwise being a pain causeing this to not auto merge, having to manually go through and set the develop ones to the ones to use, so it'll be a little before this gets merged. Like 300 changes to update 1 by 1

**Comment by JonathanMCarter** [comment]
All Done xD

**Pull request merged**
